### ISSUE TITLE
用hexo-encrypt插件时，发现插件依赖的 CryptoJS 组件和模版的 requirejs 冲突了，能不能修改模版的 requireJS 配置？

### ISSUE THREAD

**Issue by huhaifengfeng** [maochunguang/black-blue#1]

**Comment by maochunguang** [comment]
能具体点吗？

**Comment by stylovip** [comment]
[使用这个插件](https://github.com/edolphin-ydf/hexo-encrypt)给文章加密，发现加密不了，插件依赖的 CryptoJS 组件和模版的 requirejs 冲突，就是和http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js 这个js冲突

**Comment by stylovip** [comment]
![2017-08-04 3 48 30](https://user-images.githubusercontent.com/29226659/28959340-a198ab4a-792c-11e7-904d-bbbf05fe3e7a.png)

**Comment by maochunguang** [comment]
_partial/jquery.ejs修改成自己需要的jquery版本的cdn即可
