### ISSUE TITLE
jquery和requirejs引入报错，头像不能正常显示·

### ISSUE THREAD

**Issue by tony-yin** [maochunguang/black-blue#2]

**Comment by tony-yin** [comment]
解决了，将所有用到的'http://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js'全部换成'https'的，因为我是在`github.io`上面，用的是`https`，但是之前的`js`是`http`的，所以浏览器默认是阻止，认为这是不安全的行为

**Comment by maochunguang** [comment]
我的没有使用https，所以没出现你的这个问题

**Comment by tony-yin** [comment]
哦哦，我用的是git page
