### ISSUE TITLE
关于集成Gitment插件评论系统~

### ISSUE THREAD

**Issue by wangleeyom** [maochunguang/black-blue#5]
作者你好，非常喜欢你的这个主题，您能不能考虑把[Gitment](https://github.com/imsun/gitment)（或者[gitalk](https://github.com/gitalk/gitalk)）这个评论插件整合到主题里面去呢？望回复

**Comment by maochunguang** [comment]
我回头加一个整合评论的教程，可以自己加进去

**Comment by maochunguang** [comment]
新版本加进去gitment。

**Comment by maochunguang** [comment]
已经集成进去gitment

**Comment by wangleeyom** [comment]
OK，已知晓，辛苦了。

**Comment by maochunguang** [comment]
你可以试一下，gitment就一点不是很好，需要初始化。得搞个初始化脚本

**Comment by tony-yin** [comment]
你好，我用`gitalk`，但是控制台一直报错`new Gitalk`没有声明，这是咋回事啊

![image](https://user-images.githubusercontent.com/18906553/61369136-115dea00-a8c2-11e9-942a-fee1bd7c3689.png)

**Comment by tony-yin** [comment]
Fixed: `gitalk js`与`requireJS jquery`冲突，需要用`requirejs`的方式引入`Gitalk`

https://github.com/gitalk/gitalk/issues/80

Demo: https://www.tony-yin.site/
